name: teachopencadd-b

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - jupyterlab 
  - numpy
  - pandas=2.0
  - rdkit
  - pyarrow 
  - ipywidgets 
  - tqdm
  - scikit-learn
  - pip:
    - ..
