name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      - "base-ci-env-fix"
  schedule:
    # Run a cron job once weekly on Monday
    - cron: "0 3 * * 1"

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "3.8"

    env:
      PYVER: ${{ matrix.cfg.python-version }}
      PACKAGE: teachopencadd

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
          mamba-version: "*"
          # Uncomment next line if you are running the tests locally via https://github.com/nektos/act
          #miniconda-version: "latest"
          activate-environment: teachopencadd
          channel-priority: true
          environment-file: devtools/test_env.yml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps -vv

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Test CLI
        shell: bash -l {0}
        run: |
          teachopencadd -h
          pytest -v --cov=${PACKAGE} --cov-report=xml --color=yes ${PACKAGE}/tests/

      - name: Run tests
        shell: bash -l {0}
        run: |
          PYTEST_ARGS="--nbval-lax --current-env --dist loadscope --numprocesses 2"

          # Ignored notebooks
          PYTEST_IGNORE_T019_Windows="--ignore=teachopencadd/talktorials/T019_md_simulation/talktorial.ipynb"

          # Temporarily ignored notebooks
          PYTEST_IGNORE_T008="--ignore=teachopencadd/talktorials/T008_query_pdb/talktorial.ipynb"
          PYTEST_IGNORE_T021="--ignore=teachopencadd/talktorials/T021_one_hot_encoding/talktorial.ipynb"
          PYTEST_IGNORE_T022="--ignore=teachopencadd/talktorials/T022_ligand_based_screening_neural_network/talktorial.ipynb"

          if [ "$RUNNER_OS" != "Windows" ]; then
            #pytest $PYTEST_ARGS teachopencadd/talktorials/T*/talktorial.ipynb $PYTEST_IGNORE_T008 $PYTEST_IGNORE_T021 $PYTEST_IGNORE_T022
            pytest $PYTEST_ARGS teachopencadd/talktorials/T019_md_simulation/talktorial.ipynb

          else
            #pytest $PYTEST_ARGS teachopencadd/talktorials/ $PYTEST_IGNORE_T019_Windows $PYTEST_IGNORE_T008  $PYTEST_IGNORE_T021 $PYTEST_IGNORE_T022
            echo "hello"
          fi

  format:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install format dependencies
        run: python -m pip install black-nb shyaml
      - name: Run black-nb
        run: |
          black-nb -l 99 --check teachopencadd/talktorials/T*/talktorial.ipynb

  readmes:
    name: READMEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install nbformat
        run: python -m pip install nbformat shyaml
      - name: Check READMEs are up-to-date
        run: |
          for path in teachopencadd/talktorials/T*/talktorial.ipynb; do
            python devtools/regenerate_readmes.py --output README.md $path
          done
          # If the script above introduced changes (it shouldn't!), git diff will have output and an error code
          git diff --exit-code
