name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      - "dev"
      # temporarily added
      - "t019-exclude-windows-from-ci"
  schedule:
    # Run a cron job once weekly on Monday
    - cron: "0 3 * * 1"

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "3.8"

    env:
      PYVER: ${{ matrix.cfg.python-version }}
      PACKAGE: teachopencadd

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: teachopencadd
          environment-file: devtools/test_env.yml

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps -vv

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Test CLI
        shell: bash -l {0}
        run: |
          teachopencadd -h
          pytest -v --cov=${PACKAGE} --cov-report=xml --color=yes ${PACKAGE}/tests/

      - name: Run tests
        shell: bash -l {0}
        run: |
          PYTEST_ARGS="--nbval-lax --current-env --dist loadscope --numprocesses 2"

          # Ignore T019 under Windows, see https://github.com/volkamerlab/teachopencadd/issues/313
          PYTEST_IGNORE_T019="--ignore=teachopencadd/talktorials/T019_md_simulation/talktorial.ipynb"
          pytest $PYTEST_ARGS teachopencadd/talktorials/T020_md_analysis/talktorial.ipynb

          #if [ "$RUNNER_OS" != "Windows" ]; then
          #  # If not Windows, run all
          #  pytest $PYTEST_ARGS teachopencadd/talktorials/
          #else
          #  # If Windows, run all but T019
          #  pytest $PYTEST_ARGS teachopencadd/talktorials/ $PYTEST_IGNORE_T019
          #fi

  format:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install format dependencies
        run: python -m pip install black-nb shyaml
      - name: Run black-nb
        run: |
          black-nb -l 99 --check teachopencadd/talktorials/T*/talktorial.ipynb

  readmes:
    name: READMEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install nbformat
        run: python -m pip install nbformat shyaml
      - name: Check READMEs are up-to-date
        run: |
          for path in teachopencadd/talktorials/T*/talktorial.ipynb; do
            python devtools/regenerate_readmes.py --output README.md $path
          done
          # If the script above introduced changes (it shouldn't!), git diff will have output and an error code
          git diff --exit-code
