name: Docs

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "dev"
      - "maintenance/.+"
  schedule:
    # Run a cron job once weekly on Monday
    - cron: "0 3 * * 1"

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: teachopencadd
          environment-file: devtools/test_env.yml

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps -vv

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Run Sphinx
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          SPHINXOPTS="-j2 -T --keep-going" make html
          # Extra UGLY patch to fix PDF IFrame on T005
          cp talktorials/images/*.pdf _build/html/_images/
          sed -i 's|src="images/butina_full.pdf"|src="../_images/butina_full.pdf"|g' \
            _build/html/talktorials/T005_compound_clustering.html

      - name: Check 404s (Sphinx)
        shell: bash -l {0}
        run: |
          cd docs/_build/html
          npx linkinator . --verbosity error --recurse -r --retry-errors-jitter --timeout 10000 \
            -s "/*.txt" \
            -s "https://onlinelibrary.wiley.com/doi/*" \
            -s "https://wires.onlinelibrary.wiley.com/doi/*" \
            -s "https://chemistry-europe.onlinelibrary.wiley.com/doi/*" \
            -s "https://towardsdatascience.com" \
            -s "https://medium.com" \
            -s "https://*.medium.com" \
            -s "http[s]://quora.com" \
            -s "http[s]://doi.org/*" \
            -s "http[s]://pubs.acs.org/*" \
            -s "ftp://*" \
            -s "https://machinelearningmastery.com/*" \
            -s "https://www.schrodinger.com/training/videos/*" \
            -s "/*.mp4" \
            -s "/*.pdf" \
            -s "/*.png" \
            -s "https://www.icoa.fr/pkidb/index.html" \
            

      - name: Check 404s (README)
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          max-depth: 1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
